#!/bin/zsh

source ~/.zsh/plugin/zaw/zaw.zsh

source ~/.zsh/plugin/highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root)

source ~/.zsh/plugin/git-extras.zsh

. ~/.zsh/plugin/z/z.sh
if complete &>/dev/null; then
  complete -C 'z --complete "$COMP_LINE"' z
elif compctl &>/dev/null; then
  compctl -K 'z --complete "$COMP_LINE"' z
fi
function precmd () {
  z --add "$(pwd -P)"
}

export LD_PRELOAD="$HOME/.zsh/scripts/stderred/lib64/libstderred.so${LD_PRELOAD:+:$LD_PRELOAD}"

fpath=(~/.zsh/plugin/completions/src $fpath)

