#!/bin/sh
#
# Public domain
# Author: roman [] tsisyk.com
#
# Usage: ./me url [youtube-dl parameters]
#

COOKIE_FILE=/tmp/youtube-dl-cookies.txt
vlc -v -I ncurses $(youtube-dl -g --cookies ${COOKIE_FILE} $*)
